### ISSUE TITLE
read historical (and projected) monthly revenues

### ISSUE THREAD

**Issue by deanmalmgren** [datascopeanalytics/a-model#1]
This is currently read from `config.ini` in an entry that is added by hand. 

If we just do historical revenues, we can use the [quickbooks api](https://developer.intuit.com/docs/0050_quickbooks_api). Another option would be to include relatively short term cashflow projections from our google doc P&L using either [gspread](https://github.com/burnash/gspread) or [gdata](https://pythonhosted.org/gdata/docs/api.html).

**Comment by stringertheory** [comment]
just wrote a function to read the google doc P&L data, but the result is still just the raw list of lists from that spreadsheet, still needs to be parsed and used in some way

**Comment by deanmalmgren** [comment]
FWIW, that spreadsheet should probably already include the stuff that would otherwise be available from the quickbooks api, so the spreadsheet should be enough.
